### ISSUE TITLE
Install `lexd` for CI builds

### ISSUE THREAD

**Issue by reynoldsnlp** [giellalt/lang-hil#4]
@snomos and @Eijebong , it looks like we still need to install `lexd` for builds.

**Comment by reynoldsnlp** [comment]
https://github.com/giellalt/lang-hil/runs/5682155412?check_suite_focus=true

**Comment by snomos** [comment]
It seems to be an issue specifically with the CI setup - `lexd` is installed as part of the Apertium package on macOS.

**Comment by Eijebong** [comment]
Yeah looks like lexd is in a different package on ubuntu. I'll take care of that

**Comment by Eijebong** [comment]
Both documentation (https://github.com/giellalt/lang-hil/runs/5690644740?check_suite_focus=true) and package build/deployment (https://divvun-tc.thetc.se/tasks/groups/A5d-UZ1RQRWR1xrjpJIN2w) are green now, closing :)
